export const INVESTMENT_CREATE_REQUEST = "INVESTMENT_CREATE_REQUEST";
export const INVESTMENT_CREATE_SUCCESS = "INVESTMENT_CREATE_SUCCESS";
export const INVESTMENT_CREATE_FAILURE = "INVESTMENT_CREATE_FAILURE";

export const INVESTMENT_LIST_REQUEST = "INVESTMENT_LIST_REQUEST";
export const INVESTMENT_LIST_SUCCESS = "INVESTMENT_LIST_SUCCESS";
export const INVESTMENT_LIST_FAILURE = "INVESTMENT_LIST_FAILURE";

export const ADMIN_INVESTMENT_LIST_REQUEST = "ADMIN_INVESTMENT_LIST_REQUEST";
export const ADMIN_INVESTMENT_LIST_SUCCESS = "ADMIN_INVESTMENT_LIST_SUCCESS";
export const ADMIN_INVESTMENT_LIST_FAILURE = "ADMIN_INVESTMENT_LIST_FAILURE";

export const INTEREST_WITHDRAWAL_REQUEST = "INTEREST_WITHDRAWAL_REQUEST";
export const INTEREST_WITHDRAWAL_SUCCESS = "INTEREST_WITHDRAWAL_SUCCESS";
export const INTEREST_WITHDRAWAL_FAILURE = "INTEREST_WITHDRAWAL_FAILURE";
export const INTEREST_WITHDRAWAL_RESET = "INTEREST_WITHDRAWAL_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
